server:
  port: 9000


management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'


spring:
  profiles:
    active: dev
  application:
    name: web-client
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        metadata:
          # 自己这个实例的版本
          version: v1
          # 允许调用的提供者版本
          target-version: v1
#        namespace: test
#        group: xx
#        cluster-name: bb
    sentinel:
      filter:
        # 打开/关闭掉对SpringMVC端点的保护
        enabled: true
      transport:
        port: 8719
        dashboard: localhost:8080
      #默认懒加载 要调用接口才会注册到控制台
      eager: true

feign:
#  client:
#    config:
      #想要调用的服务名称
#      order-service:
      #default表示全局配置
#      default:
#        loggerLevel: NONE
  httpclient:
    # 让feign使用apache httpclient做请求；而不是默认的urlconnection
    enabled: true
    # feign的最大连接数
    max-connections: 200
    # feign单个路径的最大连接数
    max-connections-per-route: 50
  #开始sentinel 对feign的支持,默认关闭
  sentinel:
    enabled: true

logging:
  level:
    com.bryan.cloudalibaba.feignclient: debug

# 全局生效
#ribbon:
#  ConnectTimeout: 10000
#  ReadTimeout: 2000
#  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule
#  eager-load:
#    enabled: true
#    clients: order-service


#order-service生效
#order-service:
#  ribbon:
#    ConnectTimeout: 10000
#    ReadTimeout: 4000
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#关闭resttemplate的sentinel支持
#resttemplate:
#  sentinel:
#    enabled: false

